//! C++: the solution is a LeetCode-style `class Solution` in `solution.cpp`.
//! The generated driver includes dojo's support header (standard headers,
//! `using namespace std;`, `ListNode`, `TreeNode`, JSON), then the solution,
//! so the whole program is one translation unit and compiler errors in the
//! user's code are reported against `solution.cpp`.

use std::fmt::Write;
use std::path::Path;
use std::process::Command;

use super::Plan;
use crate::lang::{Language, camel};
use crate::questions::{Signature, Type};

const SUPPORT: &str = include_str!("dojo_support.hpp");
const SUPPORT_FILE: &str = "dojo_support.hpp";
const DRIVER: &str = "dojo_main.cpp";
const SOLUTION: &str = "solution.cpp";

/// GCC's catch-all header, which many LeetCode solutions include. macOS
/// lacks it, so dojo provides one (found through `-I.`).
const BITS_FILE: &str = "bits/stdc++.h";
const BITS: &str =
    "// Provided by dojo: every header LeetCode includes.\n#include \"../dojo_support.hpp\"\n";

/// The C++ type for a dojo type, as LeetCode writes it.
pub fn type_name(t: &Type) -> String {
    match t {
        Type::Int => "int".into(),
        Type::Long => "long long".into(),
        Type::Float => "double".into(),
        Type::Bool => "bool".into(),
        Type::String => "string".into(),
        Type::ListNode => "ListNode*".into(),
        Type::TreeNode => "TreeNode*".into(),
        Type::List(inner) => format!("vector<{}>", type_name(inner)),
    }
}

/// A parameter as LeetCode declares it: vectors and strings by reference,
/// scalars and node pointers by value.
fn param(t: &Type, name: &str) -> String {
    match t {
        Type::List(_) | Type::String => format!("{}& {name}", type_name(t)),
        _ => format!("{} {name}", type_name(t)),
    }
}

/// The generated `main`: decodes each parameter and calls the solution.
pub fn driver(sig: &Signature) -> String {
    let mut s = format!(
        "// Generated by dojo: calls the solution for each test case.\n#include \"{SUPPORT_FILE}\"\n#include \"{SOLUTION}\"\n\nstatic std::string dojo_case(const dojo::Json &input) {{\n"
    );
    let mut args = Vec::new();
    for (i, p) in sig.params.iter().enumerate() {
        let _ = writeln!(
            s,
            "    {} a{i} = dojo::input<{}>(input, {:?});",
            type_name(&p.ty),
            type_name(&p.ty),
            p.name
        );
        args.push(format!("a{i}"));
    }
    let _ = writeln!(
        s,
        "    Solution solution;\n    return dojo::encode(solution.{}({}));\n}}\n",
        Language::Cpp.function_name(&sig.function),
        args.join(", ")
    );
    s.push_str("int main(int argc, char **argv) { return dojo::run(argc, argv, dojo_case); }\n");
    s
}

pub fn plan(sig: &Signature, solution: &str, dir: &Path) -> Plan {
    let mut compile = Command::new(super::super::program(Language::Cpp));
    compile.args([
        "-std=c++17",
        "-O2",
        "-pthread",
        "-I.",
        "-o",
        "dojo_prog",
        DRIVER,
    ]);
    Plan {
        sources: vec![
            (DRIVER.into(), driver(sig)),
            (SUPPORT_FILE.into(), SUPPORT.into()),
            (BITS_FILE.into(), BITS.into()),
            (SOLUTION.into(), solution.into()),
        ],
        solution_file: SOLUTION.into(),
        driver_file: DRIVER.into(),
        compile,
        run: Command::new(dir.join("dojo_prog")),
    }
}

/// Starter code for a question.
pub fn boilerplate(sig: &Signature, header: &str) -> String {
    let mut s = String::new();
    for line in header.lines() {
        let _ = writeln!(s, "// {line}");
    }
    s.push('\n');
    let uses = |t: &Type| sig.returns.uses(t) || sig.params.iter().any(|p| p.ty.uses(t));
    if uses(&Type::ListNode) {
        s.push_str(
            "/**\n * Provided by dojo:\n * struct ListNode {\n *     int val;\n *     ListNode *next;\n *     ListNode() : val(0), next(nullptr) {}\n *     ListNode(int x) : val(x), next(nullptr) {}\n *     ListNode(int x, ListNode *next) : val(x), next(next) {}\n * };\n */\n\n",
        );
    }
    if uses(&Type::TreeNode) {
        s.push_str(
            "/**\n * Provided by dojo:\n * struct TreeNode {\n *     int val;\n *     TreeNode *left;\n *     TreeNode *right;\n *     TreeNode() : val(0), left(nullptr), right(nullptr) {}\n *     TreeNode(int x) : val(x), left(nullptr), right(nullptr) {}\n *     TreeNode(int x, TreeNode *left, TreeNode *right) : val(x), left(left), right(right) {}\n * };\n */\n\n",
        );
    }
    let params = sig
        .params
        .iter()
        .map(|p| param(&p.ty, &camel(&p.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = write!(
        s,
        "class Solution {{\npublic:\n    {} {}({params}) {{\n        return {};\n    }}\n}};\n",
        type_name(&sig.returns),
        Language::Cpp.function_name(&sig.function),
        zero(&sig.returns)
    );
    s
}

fn zero(t: &Type) -> &'static str {
    match t {
        Type::Int => "0",
        Type::Long => "0LL",
        Type::Float => "0.0",
        Type::Bool => "false",
        Type::String => "\"\"",
        Type::ListNode | Type::TreeNode => "nullptr",
        Type::List(_) => "{}",
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;

    fn ty(s: &str) -> Type {
        Type::parse(s).unwrap()
    }

    #[rstest]
    #[case("int", "int")]
    #[case("long", "long long")]
    #[case("float", "double")]
    #[case("bool", "bool")]
    #[case("string[]", "vector<string>")]
    #[case("int[][]", "vector<vector<int>>")]
    #[case("ListNode", "ListNode*")]
    #[case("TreeNode[]", "vector<TreeNode*>")]
    fn type_names(#[case] t: &str, #[case] expected: &str) {
        assert_eq!(type_name(&ty(t)), expected);
    }

    #[rstest]
    #[case("int[]", "vector<int>& nums")]
    #[case("string", "string& nums")]
    #[case("int", "int nums")]
    #[case("long", "long long nums")]
    #[case("TreeNode", "TreeNode* nums")]
    fn params(#[case] t: &str, #[case] expected: &str) {
        assert_eq!(param(&ty(t), "nums"), expected);
    }

    fn sig() -> Signature {
        serde_json::from_value(serde_json::json!({
            "function": "merge_lists",
            "params": [{ "name": "list_a", "type": "ListNode" }, { "name": "k", "type": "int" }],
            "returns": "ListNode[]"
        }))
        .unwrap()
    }

    #[test]
    fn driver_decodes_each_parameter() {
        let d = driver(&sig());
        assert!(
            d.contains("    ListNode* a0 = dojo::input<ListNode*>(input, \"list_a\");\n    int a1 = dojo::input<int>(input, \"k\");\n"),
            "{d}"
        );
        assert!(
            d.contains("return dojo::encode(solution.mergeLists(a0, a1));"),
            "{d}"
        );
    }

    #[test]
    fn boilerplate_is_leetcode_style() {
        let b = boilerplate(&sig(), "1. Merge (easy)\n/show");
        assert!(
            b.starts_with(
                "// 1. Merge (easy)\n// /show\n\n/**\n * Provided by dojo:\n * struct ListNode {"
            ),
            "{b}"
        );
        assert!(!b.contains("TreeNode"), "{b}");
        assert!(
            b.ends_with("class Solution {\npublic:\n    vector<ListNode*> mergeLists(ListNode* listA, int k) {\n        return {};\n    }\n};\n"),
            "{b}"
        );
    }
}
