//! Go: the solution is a plain `func` in package main, as on LeetCode.
//! `ListNode` and `TreeNode` come from dojo's support file.

use std::fmt::Write;
use std::path::Path;
use std::process::Command;

use super::Plan;
use crate::lang::{Language, camel};
use crate::questions::{Signature, Type};

const SUPPORT: &str = include_str!("dojo_support.go");
const DRIVER: &str = "dojo_main.go";
const SOLUTION: &str = "solution.go";

/// The Go type for a dojo type. `int` and `long` are both Go's `int`
/// (64-bit), as on LeetCode.
pub fn type_name(t: &Type) -> String {
    match t {
        Type::Int | Type::Long => "int".into(),
        Type::Float => "float64".into(),
        Type::Bool => "bool".into(),
        Type::String => "string".into(),
        Type::ListNode => "*ListNode".into(),
        Type::TreeNode => "*TreeNode".into(),
        Type::List(inner) => format!("[]{}", type_name(inner)),
    }
}

/// The Go type JSON decodes into: nodes arrive as arrays.
fn wire_type(t: &Type) -> String {
    match t {
        Type::ListNode => "[]int".into(),
        Type::TreeNode => "[]*int".into(),
        Type::List(inner) => format!("[]{}", wire_type(inner)),
        other => type_name(other),
    }
}

fn has_nodes(t: &Type) -> bool {
    t.uses(&Type::ListNode) || t.uses(&Type::TreeNode)
}

/// A Go expression turning `expr` (of `wire_type(t)`) into `type_name(t)`.
fn convert(t: &Type, expr: &str, depth: usize) -> String {
    match t {
        Type::ListNode => format!("dojoList({expr})"),
        Type::TreeNode => format!("dojoTree({expr})"),
        Type::List(inner) if has_nodes(inner) => {
            let x = format!("x{depth}");
            format!(
                "func(xs {wire}) {ty} {{ out := make({ty}, len(xs)); for i, {x} := range xs {{ out[i] = {inner} }}; return out }}({expr})",
                wire = wire_type(t),
                ty = type_name(t),
                inner = convert(inner, &x, depth + 1),
            )
        }
        _ => expr.to_string(),
    }
}

/// The generated `main`: decodes each parameter and calls the solution.
pub fn driver(sig: &Signature) -> String {
    let mut s = String::from(
        "// Generated by dojo: calls the solution for each test case.\npackage main\n\nimport \"encoding/json\"\n\nfunc main() {\n\tdojoRun(func(input map[string]json.RawMessage) any {\n",
    );
    let mut args = Vec::new();
    for (i, p) in sig.params.iter().enumerate() {
        let _ = writeln!(s, "\t\tvar w{i} {}", wire_type(&p.ty));
        let _ = writeln!(s, "\t\tdojoDecode(input, {:?}, &w{i})", p.name);
        args.push(convert(&p.ty, &format!("w{i}"), 0));
    }
    let _ = writeln!(
        s,
        "\t\treturn {}({})",
        Language::Go.function_name(&sig.function),
        args.join(", ")
    );
    s.push_str("\t})\n}\n");
    s
}

pub fn plan(sig: &Signature, solution: &str, dir: &Path) -> Plan {
    let mut compile = Command::new(super::super::program(Language::Go));
    compile
        .args([
            "build",
            "-o",
            "dojo_prog",
            DRIVER,
            "dojo_support.go",
            SOLUTION,
        ])
        // Never download a different Go toolchain, and build outside any
        // module the temp directory might sit in.
        .env("GOTOOLCHAIN", "local")
        .env("GO111MODULE", "off")
        .env("GOFLAGS", "");
    let mut run = Command::new(dir.join("dojo_prog"));
    // A fatal error (stack overflow) prints its reason, not every goroutine.
    run.env("GOTRACEBACK", "none");
    Plan {
        sources: vec![
            (DRIVER.into(), driver(sig)),
            ("dojo_support.go".into(), SUPPORT.into()),
            (SOLUTION.into(), solution.into()),
        ],
        solution_file: SOLUTION.into(),
        driver_file: DRIVER.into(),
        compile,
        run,
    }
}

/// Starter code for a question.
pub fn boilerplate(sig: &Signature, header: &str) -> String {
    let mut s = String::new();
    for line in header.lines() {
        let _ = writeln!(s, "// {line}");
    }
    s.push_str("package main\n\n");
    if sig.returns.uses(&Type::ListNode) || sig.params.iter().any(|p| p.ty.uses(&Type::ListNode)) {
        s.push_str("// Provided by dojo:\n// type ListNode struct {\n//     Val  int\n//     Next *ListNode\n// }\n\n");
    }
    if sig.returns.uses(&Type::TreeNode) || sig.params.iter().any(|p| p.ty.uses(&Type::TreeNode)) {
        s.push_str("// Provided by dojo:\n// type TreeNode struct {\n//     Val   int\n//     Left  *TreeNode\n//     Right *TreeNode\n// }\n\n");
    }
    let params = sig
        .params
        .iter()
        .map(|p| format!("{} {}", camel(&p.name), type_name(&p.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = write!(
        s,
        "func {}({params}) {} {{\n\treturn {}\n}}\n",
        Language::Go.function_name(&sig.function),
        type_name(&sig.returns),
        zero(&sig.returns)
    );
    s
}

fn zero(t: &Type) -> &'static str {
    match t {
        Type::Int | Type::Long | Type::Float => "0",
        Type::Bool => "false",
        Type::String => "\"\"",
        Type::ListNode | Type::TreeNode | Type::List(_) => "nil",
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;

    fn ty(s: &str) -> Type {
        Type::parse(s).unwrap()
    }

    #[rstest]
    #[case("int", "int")]
    #[case("long", "int")]
    #[case("float", "float64")]
    #[case("string[]", "[]string")]
    #[case("int[][]", "[][]int")]
    #[case("ListNode", "*ListNode")]
    #[case("TreeNode[]", "[]*TreeNode")]
    fn type_names(#[case] t: &str, #[case] expected: &str) {
        assert_eq!(type_name(&ty(t)), expected);
    }

    #[rstest]
    #[case("int[]", "w", "w")]
    #[case("ListNode", "w", "dojoList(w)")]
    #[case(
        "ListNode[]",
        "w",
        "func(xs [][]int) []*ListNode { out := make([]*ListNode, len(xs)); for i, x0 := range xs { out[i] = dojoList(x0) }; return out }(w)"
    )]
    fn conversions(#[case] t: &str, #[case] expr: &str, #[case] expected: &str) {
        assert_eq!(convert(&ty(t), expr, 0), expected);
    }
}
