//! Java: the solution is a LeetCode-style `class Solution` with an instance
//! method. `ListNode` and `TreeNode` come from dojo's support file, and
//! `java.util.*` (plus `function` and `stream`) is imported for the solution
//! as on LeetCode.

use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use super::Plan;
use crate::lang::{Language, camel};
use crate::questions::{Signature, Type};

const SUPPORT: &str = include_str!("DojoSupport.java");
const SUPPORT_FILE: &str = "DojoSupport.java";
const DRIVER: &str = "DojoMain.java";
const SOLUTION: &str = "solution.java";

/// Imports LeetCode gives every Java solution. Put on the solution's first
/// line so the user's line numbers are unchanged; repeating an import the
/// file already has is allowed.
const IMPORTS: &str =
    "import java.util.*; import java.util.function.*; import java.util.stream.*; ";

/// The Java type for a dojo type.
pub fn type_name(t: &Type) -> String {
    match t {
        Type::Int => "int".into(),
        Type::Long => "long".into(),
        Type::Float => "double".into(),
        Type::Bool => "boolean".into(),
        Type::String => "String".into(),
        Type::ListNode => "ListNode".into(),
        Type::TreeNode => "TreeNode".into(),
        Type::List(inner) => format!("{}[]", type_name(inner)),
    }
}

/// A Java expression decoding `expr` (parsed JSON: `Long`, `Double`,
/// `List<Object>`, ...) into `type_name(t)`.
fn convert(t: &Type, expr: &str, depth: usize) -> String {
    let helper = match t {
        Type::Int => "asInt",
        Type::Long => "asLong",
        Type::Float => "asDouble",
        Type::Bool => "asBool",
        Type::String => "asString",
        Type::ListNode => "toList",
        Type::TreeNode => "toTree",
        Type::List(inner) => match **inner {
            Type::Int => "ints",
            Type::Long => "longs",
            Type::Float => "doubles",
            Type::Bool => "bools",
            _ => {
                let x = format!("x{depth}");
                return format!(
                    "DojoSupport.arr({expr}, {}::new, {x} -> {})",
                    type_name(t),
                    convert(inner, &x, depth + 1)
                );
            }
        },
    };
    format!("DojoSupport.{helper}({expr})")
}

/// The generated `DojoMain`: decodes each parameter and calls the solution.
pub fn driver(sig: &Signature) -> String {
    let mut s = String::from(
        "// Generated by dojo: calls the solution for each test case.\nclass DojoMain {\n    public static void main(String[] args) throws Exception {\n        DojoSupport.run(args, input -> {\n",
    );
    let mut args = Vec::new();
    for (i, p) in sig.params.iter().enumerate() {
        let _ = writeln!(
            s,
            "            {} a{i} = {};",
            type_name(&p.ty),
            convert(&p.ty, &format!("DojoSupport.arg(input, {:?})", p.name), 0)
        );
        args.push(format!("a{i}"));
    }
    let _ = writeln!(
        s,
        "            return new Solution().{}({});",
        Language::Java.function_name(&sig.function),
        args.join(", ")
    );
    s.push_str("        });\n    }\n}\n");
    s
}

/// `java` next to the `javac` dojo compiles with, so both are the same JDK
/// (a newer javac's classes don't load in an older java).
fn java_for(javac: &str) -> PathBuf {
    let javac = Path::new(javac);
    let dir = if javac.components().count() > 1 {
        javac.parent().map(Path::to_path_buf)
    } else {
        std::env::var_os("PATH")
            .and_then(|path| std::env::split_paths(&path).find(|dir| dir.join(javac).is_file()))
    };
    match dir {
        Some(dir) if dir.join("java").is_file() => dir.join("java"),
        _ => PathBuf::from("java"),
    }
}

/// Flags for short runs: class data sharing (on by default) and the simple
/// collector start the JVM fastest; a deep stack lets recursive solutions
/// go as deep as on LeetCode.
const JAVA_FLAGS: &[&str] = &[
    "-Xss64m",
    "-Xmx1g",
    "-XX:+UseSerialGC",
    "-XX:-UsePerfData",
    "-Xshare:auto",
];

pub fn plan(sig: &Signature, solution: &str, dir: &Path) -> Plan {
    let javac = super::super::program(Language::Java);
    let mut compile = Command::new(&javac);
    compile
        // javac itself starts faster with only the quick JIT.
        .args([
            "-J-XX:TieredStopAtLevel=1",
            "-J-XX:+UseSerialGC",
            "-J-Xshare:auto",
            "-encoding",
            "UTF-8",
            "-nowarn",
            "-Xlint:none",
            "-proc:none",
            "-d",
        ])
        .arg(dir)
        .args([DRIVER, SUPPORT_FILE, SOLUTION])
        // Options from the environment would change what's compiled.
        .env_remove("JDK_JAVA_OPTIONS")
        .env_remove("JAVA_TOOL_OPTIONS")
        .env_remove("_JAVA_OPTIONS")
        .env_remove("CLASSPATH");
    let mut run = Command::new(java_for(&javac));
    run.args(JAVA_FLAGS)
        .arg("-cp")
        .arg(dir)
        .arg("DojoMain")
        .env_remove("JDK_JAVA_OPTIONS")
        .env_remove("JAVA_TOOL_OPTIONS")
        .env_remove("_JAVA_OPTIONS")
        .env_remove("CLASSPATH");
    Plan {
        sources: vec![
            (DRIVER.into(), driver(sig)),
            (SUPPORT_FILE.into(), SUPPORT.into()),
            (SOLUTION.into(), format!("{IMPORTS}{solution}")),
        ],
        solution_file: SOLUTION.into(),
        driver_file: DRIVER.into(),
        compile,
        run,
    }
}

/// Starter code for a question.
pub fn boilerplate(sig: &Signature, header: &str) -> String {
    let mut s = String::new();
    for line in header.lines() {
        let _ = writeln!(s, "// {line}");
    }
    s.push('\n');
    if sig.returns.uses(&Type::ListNode) || sig.params.iter().any(|p| p.ty.uses(&Type::ListNode)) {
        s.push_str(
            "// Provided by dojo:\n\
             // class ListNode {\n\
             //     int val;\n\
             //     ListNode next;\n\
             //     ListNode() {}\n\
             //     ListNode(int val) { this.val = val; }\n\
             //     ListNode(int val, ListNode next) { this.val = val; this.next = next; }\n\
             // }\n\n",
        );
    }
    if sig.returns.uses(&Type::TreeNode) || sig.params.iter().any(|p| p.ty.uses(&Type::TreeNode)) {
        s.push_str(
            "// Provided by dojo:\n\
             // class TreeNode {\n\
             //     int val;\n\
             //     TreeNode left;\n\
             //     TreeNode right;\n\
             //     TreeNode() {}\n\
             //     TreeNode(int val) { this.val = val; }\n\
             //     TreeNode(int val, TreeNode left, TreeNode right) {\n\
             //         this.val = val;\n\
             //         this.left = left;\n\
             //         this.right = right;\n\
             //     }\n\
             // }\n\n",
        );
    }
    let params = sig
        .params
        .iter()
        .map(|p| format!("{} {}", type_name(&p.ty), camel(&p.name)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = write!(
        s,
        "class Solution {{\n    public {} {}({params}) {{\n        return {};\n    }}\n}}\n",
        type_name(&sig.returns),
        Language::Java.function_name(&sig.function),
        zero(&sig.returns)
    );
    s
}

fn zero(t: &Type) -> &'static str {
    match t {
        Type::Int => "0",
        Type::Long => "0L",
        Type::Float => "0.0",
        Type::Bool => "false",
        Type::String => "\"\"",
        Type::ListNode | Type::TreeNode | Type::List(_) => "null",
    }
}

#[cfg(test)]
mod tests {
    use rstest::rstest;

    use super::*;

    fn ty(s: &str) -> Type {
        Type::parse(s).unwrap()
    }

    #[rstest]
    #[case("int", "int")]
    #[case("long", "long")]
    #[case("float", "double")]
    #[case("bool", "boolean")]
    #[case("string", "String")]
    #[case("string[]", "String[]")]
    #[case("int[][]", "int[][]")]
    #[case("long[]", "long[]")]
    #[case("bool[]", "boolean[]")]
    #[case("ListNode", "ListNode")]
    #[case("TreeNode[]", "TreeNode[]")]
    fn type_names(#[case] t: &str, #[case] expected: &str) {
        assert_eq!(type_name(&ty(t)), expected);
    }

    #[rstest]
    #[case("int", "v", "DojoSupport.asInt(v)")]
    #[case("int[]", "v", "DojoSupport.ints(v)")]
    #[case("ListNode", "v", "DojoSupport.toList(v)")]
    #[case(
        "string[]",
        "v",
        "DojoSupport.arr(v, String[]::new, x0 -> DojoSupport.asString(x0))"
    )]
    #[case(
        "int[][]",
        "v",
        "DojoSupport.arr(v, int[][]::new, x0 -> DojoSupport.ints(x0))"
    )]
    #[case(
        "TreeNode[][]",
        "v",
        "DojoSupport.arr(v, TreeNode[][]::new, x0 -> DojoSupport.arr(x0, TreeNode[]::new, x1 -> DojoSupport.toTree(x1)))"
    )]
    fn conversions(#[case] t: &str, #[case] expr: &str, #[case] expected: &str) {
        assert_eq!(convert(&ty(t), expr, 0), expected);
    }

    #[test]
    fn boilerplate_is_a_leetcode_solution_class() {
        let sig: Signature = serde_json::from_value(serde_json::json!({
            "function": "merge_lists",
            "params": [
                { "name": "list_a", "type": "ListNode" },
                { "name": "max_len", "type": "long" }
            ],
            "returns": "long"
        }))
        .unwrap();
        let code = boilerplate(&sig, "21. Merge (easy)\n/show to reread");
        assert!(code.starts_with(
            "// 21. Merge (easy)\n// /show to reread\n\n// Provided by dojo:\n// class ListNode {\n"
        ));
        assert!(!code.contains("TreeNode"));
        assert!(code.ends_with(
            "class Solution {\n    public long mergeLists(ListNode listA, long maxLen) {\n        return 0L;\n    }\n}\n"
        ));
    }

    #[test]
    fn java_sits_next_to_the_javac_path() {
        let dir = tempfile::tempdir().unwrap();
        for name in ["javac", "java"] {
            std::fs::write(dir.path().join(name), "").unwrap();
        }
        let javac = dir.path().join("javac");
        assert_eq!(java_for(javac.to_str().unwrap()), dir.path().join("java"));
        assert_eq!(
            java_for("/nowhere/bin/javac"),
            PathBuf::from("java"),
            "falls back to java on PATH"
        );
    }
}
